name: 提交互助码

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: sharecode
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: 提交东东工厂互助码
        run: curl -i 'http://api.turinglabs.net/api/v1/jd/ddfactory/create/P04z54XCjVWnYaS5m9RXTe8gg/'
      - name: 提交京喜工厂互助码
        run: curl -i 'http://api.turinglabs.net/api/v1/jd/jxfactory/create/GWlQwigeaeDgfZRkP61rAw==/'
      - name: 提交种豆得豆互助码
        run: curl -i 'http://api.turinglabs.net/api/v1/jd/bean/create/2suupluvyx4y5ku2jfojuul5qy/'
      - name: 提交东东农场互助码
        run: curl -i 'http://api.turinglabs.net/api/v1/jd/farm/create/c0b110b43ec748fcb2b40ff097a472cc/'
      - name: 提交东东萌宠互助码
        run: curl -i 'http://api.turinglabs.net/api/v1/jd/pet/create/MTAxODc2NTEzMjAwMDAwMDAyNjQwMDk3NQ==/'
