name: 提交互助码

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * *
  watch:
    types: started
jobs:
  run-it:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    name: sharecode
    steps:
      - name: Checkout master
        uses: actions/checkout@master
      - name: jdfarm
        run: curl -i 'http://api.turinglabs.net/api/v1/jd/farm/create/c0b110b43ec748fcb2b40ff097a472cc/'
