name: 注销京东会员卡

on:
  workflow_dispatch:
  schedule:
    - cron: '55 15 * * *'
  # watch:
  #       types: started
  # repository_dispatch:
  #   types: jd_unbind
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      URL: "https://raw.githubusercontent.com/jiegto/Actions_JX/master/jd_unbind.js"
      RUNFILE: "jd_unbind.js"
      JD_COOKIE: ${{ secrets.JD_COOKIE }}
      UN_BIND_CARD_NUM: ${{ secrets.UN_BIND_CARD_NUM }}
      UN_BIND_STOP_CARD: ${{ secrets.UN_BIND_STOP_CARD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        #with:
        #  repository: Sunert/Scripts
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node_modules
        uses: actions/cache@v2 # 使用 GitHub 官方的缓存 Action。
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-${{ env.cache-name }}-${{ hashFiles('package-lock.json') }} # 使用 package-lock.json 的 Hash 作为缓存的 key。也可以使用 package.json 代替
      - name: npm install
        if: env.JD_COOKIE
        run: |
          npm install
      - name: '运行 【注销京东会员卡】'
        if: env.JD_COOKIE
        run: |
          node actions.js
