# File: .github/workflows/repo-lxk0301.yml
name: 同步 lxk0301
on:
  schedule:
    - cron: '11 */4 * * *'
  workflow_dispatch:
  watch:
    types: started
  repository_dispatch:
    types: Sync_lxk0301
jobs:
  repo-sync:
    env:
      GIT_TOKEN: ${{ secrets.GIT_TOKEN }} #此处GIT_TOKEN需要申请，教程详见：https://www.jianshu.com/p/bb82b3ad1d11
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: sync lxk0301
        uses: repo-sync/github-sync@v2
        if: env.GIT_TOKEN
        with:
          source_repo: "https://gitee.com/lxk0301/jd_scripts.git"
          source_branch: "master"
          destination_branch: "master"
          github_token: ${{ secrets.GIT_TOKEN }}
